name: Renovate
on:
  workflow_dispatch:
#  schedule:
#    # consider running it daily or 12-hourly
#    # The "*" (#42, asterisk) character has special semantics in YAML, so this string has to be quoted.
#    - cron: '0 0 * * *' # daily https://crontab.guru/#0_0_*_*_*
#    - cron: '0 */12 * * *' # 12-hourly https://crontab.guru/#0_*/12_*_*_*
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      # you can remove this step entirely and change to a PAT for the token below
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v1
        with:
          private-key: ${{ secrets.renovate_private_key }}
          app-id: ${{ secrets.renovate_app_id }}
          owner: ${{ github.repository_owner }}
          repositories: 'Recaf'
      - name: Checkout
        uses: actions/checkout@v4.1.1
      # consider tools cache if renovate jdk != recaf jdk
      # consider repository cache if run very frequently
      # https://github.com/renovatebot/github-action#persisting-the-repository-cache
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.7
        with:
          configurationFile: renovate.json5
          # consider github app instead of PAT:
          # https://github.com/renovatebot/github-action#example-with-github-app
          # https://docs.renovatebot.com/modules/platform/github/#running-as-a-github-app
          # for PAT: token: ${{ secrets.RENOVATE_TOKEN }}
          token: '${{ steps.get_token.outputs.token }}'
        env:
          LOG_LEVEL: 'debug'